import { Router } from 'express';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

// Restrict destructive setup endpoints to local calls only. The wizard
// generates certs, runs openssl, and writes .env — not something we want
// reachable from the LAN if someone binds to 0.0.0.0 or runs behind a proxy.
function localhostOnly(req, res, next) {
  const ip = req.ip || req.connection?.remoteAddress || '';
  const isLocal =
    ip === '127.0.0.1' ||
    ip === '::1' ||
    ip === '::ffff:127.0.0.1' ||
    ip === '';
  if (!isLocal) {
    return res.status(403).json({
      error: true,
      code: 'LOCALHOST_ONLY',
      message: 'Setup endpoints are only accessible from localhost.',
    });
  }
  next();
}

// Reject any character that could break out of a KEY=VALUE line in .env
// (newline, quotes, backtick, $, backslash) or break an OAuth username format.
const SAFE_VALUE = /^[A-Za-z0-9._@+\-:/ ]*$/;
function sanitizeEnvValue(value, field) {
  if (value == null) return '';
  const str = String(value).trim();
  if (!SAFE_VALUE.test(str)) {
    const err = new Error(`Invalid characters in ${field}.`);
    err.code = 'INVALID_INPUT';
    throw err;
  }
  return str;
}

export function createSetupRouter(scrt2Client) {
  const router = Router();
  router.use('/setup', localhostOnly);

  router.get('/setup/status', (req, res) => {
    const hasEnv = fs.existsSync('.env');
    const hasCerts = fs.existsSync('certs/jwt.key') && fs.existsSync('certs/server.pem');

    let sfCliVersion = null;
    try {
      sfCliVersion = execSync('sf version', { encoding: 'utf-8' }).trim();
    } catch { /* not installed */ }

    let nodeVersion = null;
    try {
      nodeVersion = process.version;
    } catch { /* unlikely */ }

    let opensslAvailable = false;
    try {
      execSync('openssl version', { encoding: 'utf-8' });
      opensslAvailable = true;
    } catch { /* not available */ }

    res.json({
      configured: hasEnv && hasCerts,
      hasEnv,
      hasCerts,
      sfCliVersion,
      nodeVersion,
      opensslAvailable,
    });
  });

  router.post('/setup/certificate', (req, res) => {
    try {
      const certsDir = 'certs';
      if (!fs.existsSync(certsDir)) {
        fs.mkdirSync(certsDir, { recursive: true });
      }

      // Generate server HTTPS cert
      const serverKey = path.join(certsDir, 'server.key');
      const serverPem = path.join(certsDir, 'server.pem');
      if (!fs.existsSync(serverKey)) {
        execSync(
          `openssl req -x509 -newkey rsa:2048 -keyout ${serverKey} -out ${serverPem} -days 365 -nodes -subj "/CN=VoxCanvas Local Dev"`,
          { stdio: 'pipe' }
        );
        fs.chmodSync(serverKey, 0o600);
      }

      // Generate JWT key pair
      const jwtKey = path.join(certsDir, 'jwt.key');
      const jwtPem = path.join(certsDir, 'jwt.pem');
      if (!fs.existsSync(jwtKey)) {
        execSync(`openssl genrsa -out ${jwtKey} 2048`, { stdio: 'pipe' });
        execSync(
          `openssl req -new -x509 -key ${jwtKey} -out ${jwtPem} -days 365 -subj "/CN=VoxCanvas JWT"`,
          { stdio: 'pipe' }
        );
        fs.chmodSync(jwtKey, 0o600);
      }

      res.json({ success: true, jwtCertPath: jwtPem });
    } catch (err) {
      res.status(500).json({
        error: true,
        code: 'CERT_GENERATION_FAILED',
        message: err.message,
      });
    }
  });

  router.get('/setup/certificate/download', (req, res) => {
    const jwtPem = 'certs/jwt.pem';
    if (!fs.existsSync(jwtPem)) {
      return res.status(404).json({
        error: true,
        code: 'CERT_NOT_FOUND',
        message: 'JWT certificate not generated yet. Run certificate generation first.',
      });
    }
    res.download(path.resolve(jwtPem), 'jwt.pem');
  });

  router.post('/setup/complete', (req, res) => {
    try {
      const { scrtBaseUrl, orgId, callCenterApiName, callCenterPhone } = req.body;
      if (!scrtBaseUrl || !orgId || !callCenterApiName) {
        return res.status(400).json({
          error: true,
          code: 'MISSING_FIELDS',
          message: 'scrtBaseUrl, orgId, and callCenterApiName are required.',
        });
      }

      const safe = {
        scrtBaseUrl: sanitizeEnvValue(scrtBaseUrl, 'scrtBaseUrl'),
        orgId: sanitizeEnvValue(orgId, 'orgId'),
        callCenterApiName: sanitizeEnvValue(callCenterApiName, 'callCenterApiName'),
        callCenterPhone: sanitizeEnvValue(callCenterPhone || '', 'callCenterPhone'),
      };

      const envContent = `# VoxCanvas Configuration (generated by Setup Wizard)
SERVER_PORT=3030
SERVER_HOST=127.0.0.1

# Certificate Paths
SF_PRIVATE_KEY_PATH=certs/jwt.key
HTTPS_CERT_PATH=certs/server.pem
HTTPS_KEY_PATH=certs/server.key

# Salesforce Tenant / Contact Center
SF_SCRT_BASE_URL=${safe.scrtBaseUrl}
SF_ORG_ID=${safe.orgId}
CALL_CENTER_API_NAME=${safe.callCenterApiName}
CALL_CENTER_PHONE=${safe.callCenterPhone}
`;

      fs.writeFileSync('.env', envContent);
      fs.chmodSync('.env', 0o600);

      scrt2Client.configure({
        scrtBaseUrl: safe.scrtBaseUrl,
        orgId: safe.orgId,
        callCenterApiName: safe.callCenterApiName,
      });

      res.json({ success: true, message: 'Configuration saved.' });
    } catch (err) {
      const status = err.code === 'INVALID_INPUT' ? 400 : 500;
      res.status(status).json({
        error: true,
        code: err.code || 'SAVE_FAILED',
        message: err.message,
      });
    }
  });

  return router;
}
