import { Router } from 'express';
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

export function createSetupRouter(scrt2Client) {
  const router = Router();

  router.get('/setup/status', (req, res) => {
    const hasEnv = fs.existsSync('.env');
    const hasCerts = fs.existsSync('certs/jwt.key') && fs.existsSync('certs/server.pem');
    const hasConsumerKey = !!process.env.SF_CONSUMER_KEY;

    let sfCliVersion = null;
    try {
      sfCliVersion = execSync('sf version', { encoding: 'utf-8' }).trim();
    } catch { /* not installed */ }

    let nodeVersion = null;
    try {
      nodeVersion = process.version;
    } catch { /* unlikely */ }

    let opensslAvailable = false;
    try {
      execSync('openssl version', { encoding: 'utf-8' });
      opensslAvailable = true;
    } catch { /* not available */ }

    res.json({
      configured: hasEnv && hasCerts && hasConsumerKey,
      hasEnv,
      hasCerts,
      hasConsumerKey,
      sfCliVersion,
      nodeVersion,
      opensslAvailable,
    });
  });

  router.post('/setup/certificate', (req, res) => {
    try {
      const certsDir = 'certs';
      if (!fs.existsSync(certsDir)) {
        fs.mkdirSync(certsDir, { recursive: true });
      }

      // Generate server HTTPS cert
      const serverKey = path.join(certsDir, 'server.key');
      const serverPem = path.join(certsDir, 'server.pem');
      if (!fs.existsSync(serverKey)) {
        execSync(
          `openssl req -x509 -newkey rsa:2048 -keyout ${serverKey} -out ${serverPem} -days 365 -nodes -subj "/CN=VoxCanvas Local Dev"`,
          { stdio: 'pipe' }
        );
      }

      // Generate JWT key pair
      const jwtKey = path.join(certsDir, 'jwt.key');
      const jwtPem = path.join(certsDir, 'jwt.pem');
      if (!fs.existsSync(jwtKey)) {
        execSync(`openssl genrsa -out ${jwtKey} 2048`, { stdio: 'pipe' });
        execSync(
          `openssl req -new -x509 -key ${jwtKey} -out ${jwtPem} -days 365 -subj "/CN=VoxCanvas JWT"`,
          { stdio: 'pipe' }
        );
      }

      res.json({ success: true, jwtCertPath: jwtPem });
    } catch (err) {
      res.status(500).json({
        error: true,
        code: 'CERT_GENERATION_FAILED',
        message: err.message,
      });
    }
  });

  router.get('/setup/certificate/download', (req, res) => {
    const jwtPem = 'certs/jwt.pem';
    if (!fs.existsSync(jwtPem)) {
      return res.status(404).json({
        error: true,
        code: 'CERT_NOT_FOUND',
        message: 'JWT certificate not generated yet. Run certificate generation first.',
      });
    }
    res.download(path.resolve(jwtPem), 'jwt.pem');
  });

  router.post('/setup/complete', (req, res) => {
    try {
      const { consumerKey, username, loginUrl } = req.body;
      if (!consumerKey || !username) {
        return res.status(400).json({
          error: true,
          code: 'MISSING_FIELDS',
          message: 'consumerKey and username are required.',
        });
      }

      const envContent = `# VoxCanvas Configuration (generated by Setup Wizard)
SERVER_PORT=3030
SERVER_HOST=127.0.0.1

# Salesforce Connected App
SF_CONSUMER_KEY=${consumerKey}
SF_USERNAME=${username}
SF_LOGIN_URL=${loginUrl || 'https://login.salesforce.com'}

# Certificate Paths
SF_PRIVATE_KEY_PATH=certs/jwt.key
HTTPS_CERT_PATH=certs/server.pem
HTTPS_KEY_PATH=certs/server.key

# Contact Center (configured at runtime via /api/tenant/configure)
CALL_CENTER_API_NAME=
CALL_CENTER_PHONE=
`;

      fs.writeFileSync('.env', envContent);
      res.json({ success: true, message: 'Configuration saved. Restart server to apply.' });
    } catch (err) {
      res.status(500).json({
        error: true,
        code: 'SAVE_FAILED',
        message: err.message,
      });
    }
  });

  return router;
}
